package com.ss.Manager;

public class Demo {
	
	/*
	 * SET LINESIZE 200; SET PAGESIZE 50; SET WRAP OFF;
	 * 
	 * COLUMN ID FORMAT 9999 HEADING "ID"; COLUMN NAME FORMAT A25 HEADING "Name";
	 * COLUMN CITY FORMAT A20 HEADING "City"; COLUMN STATE FORMAT A15 HEADING
	 * "State"; COLUMN PINCODE FORMAT A10 HEADING "Pincode"; COLUMN MOBILE_NUMBER
	 * FORMAT 9999999999 HEADING "Mobile"; COLUMN PARENT_MOBILE_NUMBER FORMAT
	 * 9999999999 HEADING "Parent No"; COLUMN COUNT_OF_DUE FORMAT 999 HEADING "Due";
	 * COLUMN DATE_OF_JOINING FORMAT A12 HEADING "Join Date"; COLUMN DUE_DATE FORMAT
	 * A12 HEADING "Due Date"; COLUMN AADHAR_HEADING FORMAT A10 HEADING "Aadhar";
	 * COLUMN PAN_HEADING FORMAT A10 HEADING "PAN";
	 * 
	 * SELECT ID, NAME, CITY, STATE, PINCODE, MOBILE_NUMBER, PARENT_MOBILE_NUMBER,
	 * COUNT_OF_DUE, TO_CHAR(DATE_OF_JOINING, 'DD-MON-YYYY') AS DATE_OF_JOINING,
	 * TO_CHAR(DUE_DATE, 'DD-MON-YYYY') AS DUE_DATE, CASE WHEN AADHAR_CARD IS NOT
	 * NULL THEN '✅ YES' ELSE '❌ NO' END AS AADHAR_HEADING, CASE WHEN PAN_CARD IS
	 * NOT NULL THEN '✅ YES' ELSE '❌ NO' END AS PAN_HEADING FROM STUDENTS;
	 * 
	 */
}
